apiVersion: v1
kind: ReplicationController
metadata:
  name: pythonwdiscord
spec:
  replicas: 1
  selector:
    app: pythonwdiscord
  template:
    metadata:
      labels:
        app: pythonwdiscord
      name: pythonwdiscord
    spec:
      containers:
      - image: karulean/kubernetes-deployment:experimental
        imagePullPolicy: Always
        name: experimental
        